name: test

on:
  push:
    branches:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Install go
        uses: actions/setup-go@v2
        with:
          stable: true

      - name: Install winfsp and winfsp-tests (Windows)
        if: runner.os == 'Windows'
        run: |
          $releases = Invoke-WebRequest https://api.github.com/repos/billziss-gh/winfsp/releases | `
              ConvertFrom-Json

          $asseturi = $releases[0].assets.browser_download_url | `
              Where-Object { $_ -match "winfsp-.*\.msi" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp.msi
          Start-Process -NoNewWindow -Wait msiexec "/i winfsp.msi /qn"

          $asseturi = $releases[0].assets.browser_download_url | `
              Where-Object { $_ -match "winfsp-tests-.*\.zip" }
          Invoke-WebRequest -Uri $asseturi -Out winfsp-tests.zip
          Expand-Archive -Path winfsp-tests.zip
          Copy-Item "C:\Program Files (x86)\WinFsp\bin\winfsp-x64.dll" winfsp-tests

      - name: Install FUSE and secfs.test (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get -qq install libfuse-dev
          sudo apt-get -qq install libacl1-dev
          git clone -q https://github.com/billziss-gh/secfs.test.git secfs.test
          git -C secfs.test checkout -q edf5eb4a108bfb41073f765aef0cdd32bb3ee1ed
          sed -e 's/^fs=.*$/fs="cgofuse"/' -i""  secfs.test/fstest/fstest/tests/conf
          make -C secfs.test

      - name: Build HUBFS (Windows)
        if: runner.os == 'Windows'
        run: |
          .\make.cmd win

      - name: Build HUBFS (Linux)
        if: runner.os == 'Linux'
        run: |
          make lnx

      - name: Test go packages (Windows)
        if: runner.os == 'Windows'
        #env:
        #  GITHUB_TOKEN: ${{ github.token }}
        run: |
          Set-Location src
          $env:CGO_ENABLED=0
          go test -v -count=1 ./...

      - name: Test go packages (Linux)
        if: runner.os == 'Linux'
        #env:
        #  GITHUB_TOKEN: ${{ github.token }}
        run: |
          cd src
          go test -v -count=1 ./...

      - name: Test component file systems (Windows)
        if: runner.os == 'Windows'
        run: |
          Set-PSDebug -Trace 1

          $testexe = (Get-Item winfsp-tests\winfsp-tests-x64.exe)
          Set-Location src
          New-Item -Type Directory -Path hi,lo >$null
          $env:CGO_ENABLED=0

          go build _tools/ptfs.go
          go build _tools/unionfs.go

          Start-Process -NoNewWindow .\ptfs.exe "-o uid=-1,rellinks,FileInfoTimeout=-1 lo X:"
          Start-Sleep 3
          Push-Location X:\
          . $testexe --fuse-external --resilient --case-insensitive-cmp `
              +* `
              -create_fileattr_test `
              -delete_access_test `
              -delete_ex_test `
              -create_backup_test `
              -create_restore_test `
              -rename_flipflop_test `
              -exec_rename_dir_test `
              -reparse_nfs_test `
              -ea*
          Stop-Process -Name ptfs
          Start-Sleep 3
          Pop-Location

          Start-Process -NoNewWindow .\unionfs.exe "-o uid=-1,rellinks,FileInfoTimeout=-1 hi lo X:"
          Start-Sleep 3
          Push-Location X:\
          . $testexe --fuse-external --resilient --case-insensitive-cmp `
              +* `
              -create_fileattr_test `
              -delete_access_test `
              -delete_ex_test `
              -create_backup_test `
              -create_restore_test `
              -rename_flipflop_test `
              -exec_rename_dir_test `
              -reparse_nfs_test `
              -ea*
          Stop-Process -Name unionfs
          Start-Sleep 3
          Pop-Location

      - name: Test component file systems (Linux)
        if: runner.os == 'Linux'
        run: |
          set -x

          cd src
          mkdir lo hi mnt

          go build _tools/ptfs.go
          go build _tools/unionfs.go

          sudo ./ptfs -o allow_other,default_permissions,use_ino,attr_timeout=0 lo mnt &
          sleep 3
          (cd mnt && sudo prove -fr ../../secfs.test/fstest/fstest/tests)
          sudo umount mnt

          sudo ./unionfs -o allow_other,default_permissions,use_ino,attr_timeout=0 hi lo mnt &
          sleep 3
          (cd mnt && sudo prove -fr ../../secfs.test/fstest/fstest/tests)
          (cd mnt && ../../secfs.test/tools/bin/fsx -N 50000 test xxxxxx)
          seed=$(date +%s)
          ../secfs.test/tools/bin/fsstress -d mnt -s $seed -n 5000 -p 10 -S
          ../secfs.test/tools/bin/fsstress -d mnt -s $seed -n 5000 -p 10 -S
          sudo umount mnt
